"""Ingest tests for cloud/HSM scanner output (plan Phase 4, R6 and R7).

The golden document is **real scanner output** — live AWS KMS calls against a
local emulator, plus a PKCS#11 inventory export — regenerated by
``go run ./cloudhsm/cmd/gencbom``.

The property this file exists to prove is the asset-type round trip.
``hardware_module``, ``cloud_service`` and ``key`` all serialise to the single
CycloneDX spelling ``related-crypto-material``; only the
``trinetra:asset-type`` property tells them apart. If that breaks, an HSM and a
KMS key become indistinguishable in the inventory.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.models.enums import (
    AssetType,
    CloudProvider,
    CloudServiceKind,
    KeyManagementKind,
    ScannerKind,
)
from app.services.cbom_ingest import ingest_document, validate_document

REPO_ROOT = Path(__file__).resolve().parents[3]
GOLDEN = REPO_ROOT / "tests" / "golden" / "cloudhsm-fixtures.cbom.json"

SCAN_TARGET = "aws:ap-south-1"


@pytest.fixture
def golden_document() -> dict:
    if not GOLDEN.exists():
        pytest.skip(f"golden cloud/HSM CBOM not generated: {GOLDEN}")
    return json.loads(GOLDEN.read_text(encoding="utf-8"))


class TestCloudHSMGoldenDocument:
    def test_golden_document_validates(self, golden_document: dict) -> None:
        validate_document(golden_document)

    def test_golden_document_ingests_without_gaps(self, golden_document: dict) -> None:
        result = ingest_document(
            golden_document,
            scan_target=SCAN_TARGET,
            discovered_by=ScannerKind.CLOUD_HSM,
        )
        assert result.artefact_count > 0
        assert result.gaps == [], f"unexpected gaps: {result.gaps}"

    def test_hardware_modules_and_cloud_services_stay_distinct(
        self, golden_document: dict
    ) -> None:
        """The asset-type round trip, which is what this phase depends on.

        All three types share one wire spelling; without the hint an HSM would
        ingest as a generic related-material artefact and the risk engine could
        not tell a hardware purchase from a code change.
        """
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)
        types = {artefact.asset_type for artefact in result.artefacts}

        assert AssetType.HARDWARE_MODULE in types, f"got {types}"
        assert AssetType.CLOUD_SERVICE in types, f"got {types}"
        assert AssetType.KEY in types, f"got {types}"

    def test_kms_key_specs_survive(self, golden_document: dict) -> None:
        """RSA_2048 in a KMS is Shor-breakable; the spec must reach the model.

        A cloud key is described by ``key_spec`` rather than a bare size: the
        provider's own string (RSA_2048, SYMMETRIC_DEFAULT) is more
        informative than an integer, and a reader can check it against the
        AWS console verbatim.
        """
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        specs = {
            artefact.detail.key_spec
            for artefact in result.artefacts
            if artefact.asset_type is AssetType.CLOUD_SERVICE
            and artefact.detail is not None
            and artefact.detail.key_spec
        }
        assert "RSA_2048" in specs, f"Shor-breakable KMS key spec missing; got {specs}"
        assert "SYMMETRIC_DEFAULT" in specs, f"got {specs}"

    def test_kms_ownership_survives(self, golden_document: dict) -> None:
        """Who controls a key decides code change vs vendor negotiation."""
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        managements = {
            artefact.detail.key_management
            for artefact in result.artefacts
            if artefact.asset_type is AssetType.CLOUD_SERVICE
            and artefact.detail is not None
        }
        assert KeyManagementKind.CUSTOMER_MANAGED in managements, f"got {managements}"

    def test_kms_provider_and_region_survive(self, golden_document: dict) -> None:
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        for artefact in result.artefacts:
            if artefact.asset_type is not AssetType.CLOUD_SERVICE:
                continue
            assert artefact.detail is not None
            assert artefact.detail.provider is CloudProvider.AWS
            assert artefact.detail.service is CloudServiceKind.KMS
            assert artefact.detail.region == "ap-south-1"
            # The ARN is how an operator finds the key in the console.
            assert artefact.detail.resource_id, f"{artefact.name} has no resource id"
            return
        pytest.fail("no cloud-service artefacts in the golden document")

    def test_hsm_key_sizes_survive(self, golden_document: dict) -> None:
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        sizes = {
            artefact.detail.size_bits
            for artefact in result.artefacts
            if artefact.asset_type is AssetType.KEY
            and artefact.detail is not None
            and getattr(artefact.detail, "size_bits", None)
        }
        assert 2048 in sizes, f"HSM RSA key size missing; got {sizes}"

    def test_no_secret_material_reaches_the_model(self, golden_document: dict) -> None:
        """A KMS and an HSM exist so key material never leaves them."""
        serialised = json.dumps(golden_document)

        for forbidden in (
            "CKA_VALUE",
            "PRIVATE KEY-----",
            "SecretAccessKey",
            "AWS4-HMAC",
            "Authorization",
        ):
            assert forbidden not in serialised, f"document contains {forbidden!r}"

    def test_every_artefact_has_a_resource_identifier(
        self, golden_document: dict
    ) -> None:
        """Evidence here is a resource id, not a file path, but it must exist.

        An artefact nobody can locate cannot be verified or remediated.
        """
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        for artefact in result.artefacts:
            assert artefact.evidence, f"{artefact.name} has no evidence"
            path = artefact.evidence[0].location.path
            assert path, f"{artefact.name} has no resource identifier"
            assert not path.startswith("/"), f"absolute path in evidence: {path}"
            assert path.startswith(("aws/", "pkcs11/")), (
                f"unrecognised resource identifier: {path}"
            )

    def test_pqc_capability_is_recorded_for_hsms(self, golden_document: dict) -> None:
        """Whether an HSM can do PQC decides firmware change vs hardware purchase."""
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        modules = [
            artefact
            for artefact in result.artefacts
            if artefact.asset_type is AssetType.HARDWARE_MODULE
        ]
        assert modules, "no hardware modules in the golden document"

        notes = " ".join(
            artefact.evidence[0].additional_context or "" for artefact in modules
        )
        assert "PQC" in notes, f"no PQC capability recorded: {notes}"
        # One fixture HSM advertises ML-DSA and one does not; both verdicts
        # must be present, so neither is being defaulted.
        assert "advertises PQC mechanisms" in notes
        assert "no PQC mechanisms" in notes

    def test_every_contributing_tool_is_recorded(self, golden_document: dict) -> None:
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)
        names = {tool.name for tool in result.tools}

        assert "cloudhsm-scanner" in names
        for expected in ("aws-kms-scanner", "pkcs11-scanner"):
            assert expected in names, f"{expected} missing from metadata.tools"

    def test_ingest_is_idempotent(self, golden_document: dict) -> None:
        first = ingest_document(golden_document, scan_target=SCAN_TARGET)
        second = ingest_document(golden_document, scan_target=SCAN_TARGET)

        assert {a.artefact_id for a in first.artefacts} == {
            a.artefact_id for a in second.artefacts
        }
