"""Ingest tests for container-scanner output (plan task 3.x).

The golden document is **real scanner output**, regenerated by
``go run ./container/cmd/gencbom``. Phase 2 proved ingest handles algorithms;
this proves it handles the asset types only the container scanner produces:
certificates, keys, libraries and declared protocols.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.models.enums import AssetType, ScannerKind
from app.services.cbom_ingest import ingest_document, validate_document

REPO_ROOT = Path(__file__).resolve().parents[3]
GOLDEN = REPO_ROOT / "tests" / "golden" / "deployment-fixtures.cbom.json"

SCAN_TARGET = "image:registry.example.org/payments-api:1.2.3"


@pytest.fixture
def golden_document() -> dict:
    if not GOLDEN.exists():
        pytest.skip(f"golden container CBOM not generated: {GOLDEN}")
    return json.loads(GOLDEN.read_text(encoding="utf-8"))


class TestContainerGoldenDocument:
    def test_golden_document_validates(self, golden_document: dict) -> None:
        validate_document(golden_document)

    def test_golden_document_ingests_without_gaps(self, golden_document: dict) -> None:
        result = ingest_document(
            golden_document,
            scan_target=SCAN_TARGET,
            discovered_by=ScannerKind.CONTAINER,
        )
        assert result.artefact_count > 0
        assert result.gaps == [], f"unexpected gaps: {result.gaps}"

    def test_all_container_asset_types_survive(self, golden_document: dict) -> None:
        """Certificates, libraries and protocols must each reach the model."""
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)
        types = {artefact.asset_type for artefact in result.artefacts}

        assert AssetType.CERTIFICATE in types
        assert AssetType.LIBRARY in types
        assert AssetType.PROTOCOL in types

    def test_certificate_key_sizes_survive(self, golden_document: dict) -> None:
        """A certificate's public-key size is the R19 field that matters most.

        RSA-2048 is Shor-breakable; the risk engine cannot say so without the
        size reaching the artefact.
        """
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        # A certificate's size lives in ``public_key_size_bits``, not
        # ``key_size_bits``: the subject's public key is a different thing from
        # an algorithm's key size, and the model keeps them apart on purpose.
        sizes = {
            artefact.detail.public_key_size_bits
            for artefact in result.artefacts
            if artefact.asset_type is AssetType.CERTIFICATE
            and artefact.detail is not None
            and artefact.detail.public_key_size_bits
        }
        assert 2048 in sizes, f"RSA-2048 certificate size missing; got {sizes}"

    def test_certificate_curve_survives(self, golden_document: dict) -> None:
        """P-256 is what makes an EC certificate's strength legible."""
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        curves = {
            artefact.detail.public_key_curve
            for artefact in result.artefacts
            if artefact.asset_type is AssetType.CERTIFICATE
            and artefact.detail is not None
            and artefact.detail.public_key_curve
        }
        assert "P-256" in curves, f"EC curve missing; got {curves}"

    def test_protocols_are_marked_declared_not_observed(
        self, golden_document: dict
    ) -> None:
        """A config file states intent; only a live handshake states fact.

        Phase 11A observes. Until then every protocol artefact must say it was
        declared, or a fix that was never deployed would read as deployed.
        """
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        protocols = [
            artefact
            for artefact in result.artefacts
            if artefact.asset_type is AssetType.PROTOCOL
        ]
        assert protocols, "no protocol artefacts in the golden document"

        for protocol in protocols:
            assert protocol.detail is not None
            assert protocol.detail.is_observed is False, (
                f"protocol {protocol.name!r} claims to be observed"
            )

    def test_libraries_carry_no_algorithm(self, golden_document: dict) -> None:
        """OpenSSL being installed proves an implementation exists, not a use."""
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        libraries = [
            artefact
            for artefact in result.artefacts
            if artefact.asset_type is AssetType.LIBRARY
        ]
        assert libraries, "no library artefacts in the golden document"

        for library in libraries:
            assert library.algorithm is None, (
                f"library {library.name!r} carries algorithm {library.algorithm!r}"
            )

    def test_no_secret_material_reaches_the_model(self, golden_document: dict) -> None:
        """The single most important property of the container scanner."""
        serialised = json.dumps(golden_document)

        for forbidden in ("PRIVATE KEY-----", "BEGIN RSA PRIVATE", "BEGIN EC PRIVATE"):
            assert forbidden not in serialised, f"document contains {forbidden!r}"

    def test_every_artefact_has_verifiable_evidence(
        self, golden_document: dict
    ) -> None:
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        for artefact in result.artefacts:
            assert artefact.evidence, f"{artefact.name} has no evidence"
            path = artefact.evidence[0].location.path
            assert path, f"{artefact.name} has no evidence path"
            # A host path would leak the scanner's filesystem layout.
            assert not path.startswith("/"), f"absolute path in evidence: {path}"

    def test_evidence_paths_use_forward_slashes(self, golden_document: dict) -> None:
        """Paths must read identically whether produced on Linux or Windows."""
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)

        for artefact in result.artefacts:
            path = artefact.evidence[0].location.path
            assert "\\" not in path, f"backslash in evidence path: {path}"

    def test_every_contributing_tool_is_recorded(self, golden_document: dict) -> None:
        """A CBOM that cannot say what produced it is not an audit artefact."""
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)
        names = {tool.name for tool in result.tools}

        assert "container-scanner" in names
        for expected in ("pki-scanner", "config-scanner"):
            assert expected in names, f"{expected} missing from metadata.tools"

    def test_ingest_is_idempotent(self, golden_document: dict) -> None:
        first = ingest_document(golden_document, scan_target=SCAN_TARGET)
        second = ingest_document(golden_document, scan_target=SCAN_TARGET)

        assert {a.artefact_id for a in first.artefacts} == {
            a.artefact_id for a in second.artefacts
        }

    def test_source_and_container_scans_yield_distinct_identities(
        self, golden_document: dict
    ) -> None:
        """The same target scanned two ways must not collide.

        Artefact identity includes the scan target, so a repository scan and an
        image scan of the same application stay separate inventories rather than
        overwriting each other.
        """
        image = ingest_document(golden_document, scan_target="image:app:1.0")
        repo = ingest_document(golden_document, scan_target="https://git/app")

        assert {a.artefact_id for a in image.artefacts}.isdisjoint(
            {a.artefact_id for a in repo.artefacts}
        )
