"""Ingest tests (plan task 2.6).

The golden document these tests read is **real scanner output**, regenerated by
``go run ./source/cmd/gencbom``. Testing against a hand-written approximation
would let the two sides drift while every test stayed green.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.models.enums import (
    AssetType,
    CipherMode,
    Confidence,
    DetectionMethod,
    Primitive,
    ScannerKind,
)
from app.services.cbom_ingest import (
    CBOMValidationError,
    ingest_document,
    validate_document,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
GOLDEN = REPO_ROOT / "tests" / "golden" / "positive-fixtures.cbom.json"

SCAN_TARGET = "https://git.example.org/payments-api"


@pytest.fixture
def golden_document() -> dict:
    if not GOLDEN.exists():
        pytest.skip(f"golden CBOM not generated: {GOLDEN}")
    return json.loads(GOLDEN.read_text(encoding="utf-8"))


def minimal_document(**overrides) -> dict:
    document = {
        "bomFormat": "CycloneDX",
        "specVersion": "1.6",
        "serialNumber": "urn:uuid:11111111-2222-3333-4444-555555555555",
        "version": 1,
        "metadata": {
            "timestamp": "2026-03-14T10:30:00Z",
            "tools": [
                {"vendor": "Trinetra", "name": "source-scanner", "version": "0.2.0"}
            ],
        },
        "components": [],
    }
    document.update(overrides)
    return document


def crypto_component(**overrides) -> dict:
    component = {
        "type": "cryptographic-asset",
        "bom-ref": "trinetra:abc123",
        "name": "RSA-2048",
        "cryptoProperties": {
            "assetType": "algorithm",
            "algorithmProperties": {
                "primitive": "pke",
                "parameterSetIdentifier": "2048",
                "cryptoFunctions": ["encapsulate"],
            },
        },
        "evidence": {"occurrences": [{"location": "svc/auth.py", "line": 20}]},
        "properties": [
            {"name": "trinetra:key-size-bits", "value": "2048"},
            {"name": "trinetra:detection-method", "value": "semgrep_pattern"},
            {"name": "trinetra:confidence", "value": "high"},
            {"name": "trinetra:algorithm", "value": "rsa"},
        ],
    }
    component.update(overrides)
    return component


class TestValidation:
    """Validation happens twice by design; this is the Python half."""

    def test_valid_document_passes(self) -> None:
        validate_document(minimal_document())

    @pytest.mark.parametrize(
        ("overrides", "expected"),
        [
            ({"bomFormat": "SPDX"}, "bomFormat"),
            ({"specVersion": "1.5"}, "specVersion"),
            ({"serialNumber": "not-a-urn"}, "serialNumber"),
        ],
    )
    def test_contract_violations_are_rejected(self, overrides, expected) -> None:
        with pytest.raises(CBOMValidationError) as excinfo:
            validate_document(minimal_document(**overrides))
        assert expected in str(excinfo.value)

    def test_missing_tools_is_rejected(self) -> None:
        """A CBOM that cannot say what produced it is not an audit artefact."""
        document = minimal_document()
        document["metadata"]["tools"] = []
        with pytest.raises(CBOMValidationError, match=r"metadata\.tools"):
            validate_document(document)

    def test_all_problems_are_reported_together(self) -> None:
        with pytest.raises(CBOMValidationError) as excinfo:
            validate_document({"bomFormat": "SPDX", "specVersion": "1.4"})
        assert len(excinfo.value.problems) >= 3


class TestIngest:
    def test_zero_components_is_a_valid_result(self) -> None:
        """A repository genuinely free of cryptography is a real answer."""
        result = ingest_document(minimal_document(), scan_target=SCAN_TARGET)
        assert result.artefact_count == 0
        assert result.gaps == []

    def test_crypto_component_becomes_an_artefact(self) -> None:
        result = ingest_document(
            minimal_document(components=[crypto_component()]),
            scan_target=SCAN_TARGET,
        )
        assert result.artefact_count == 1

        artefact = result.artefacts[0]
        assert artefact.asset_type is AssetType.ALGORITHM
        assert artefact.name == "RSA-2048"
        assert artefact.algorithm == "rsa"
        assert artefact.primitive is Primitive.PKE
        assert artefact.detail is not None
        assert artefact.detail.key_size_bits == 2048

    def test_evidence_is_preserved(self) -> None:
        result = ingest_document(
            minimal_document(components=[crypto_component()]),
            scan_target=SCAN_TARGET,
        )
        evidence = result.artefacts[0].evidence[0]

        assert evidence.location.path == "svc/auth.py"
        assert evidence.location.line == 20
        assert evidence.detection_method is DetectionMethod.SEMGREP_PATTERN
        assert evidence.confidence is Confidence.HIGH

    def test_raw_component_is_preserved_verbatim(self) -> None:
        """Nothing a scanner produced is ever lost, even if unmodelled."""
        component = crypto_component()
        component["properties"].append(
            {"name": "trinetra:future-field", "value": "unmodelled"}
        )
        result = ingest_document(
            minimal_document(components=[component]), scan_target=SCAN_TARGET
        )
        assert result.artefacts[0].raw_cbom == component

    def test_non_crypto_components_are_skipped_not_rejected(self) -> None:
        """Real CBOMs legitimately contain other component types."""
        document = minimal_document(
            components=[
                {"type": "library", "name": "bouncycastle", "version": "1.70"},
                crypto_component(),
                {"type": "application", "name": "payments-api"},
            ]
        )
        result = ingest_document(document, scan_target=SCAN_TARGET)

        assert result.artefact_count == 1
        assert result.skipped_components == 2

    def test_component_without_a_location_becomes_a_gap(self) -> None:
        """An unsourced finding is a bug; the loss must be visible."""
        document = minimal_document(
            components=[crypto_component(evidence={"occurrences": []})]
        )
        result = ingest_document(document, scan_target=SCAN_TARGET)

        assert result.artefact_count == 0
        assert len(result.gaps) == 1
        assert "could not be ingested" in result.gaps[0].reason

    def test_one_bad_component_does_not_discard_the_rest(self) -> None:
        document = minimal_document(
            components=[
                crypto_component(name=""),  # unnameable
                crypto_component(name="AES-128-CBC"),
            ]
        )
        result = ingest_document(document, scan_target=SCAN_TARGET)

        assert result.artefact_count == 1
        assert len(result.gaps) == 1


class TestP3AbsentMeansUnobserved:
    """A missing value stays missing, so the artefact degrades honestly."""

    def test_unstated_key_size_stays_none(self) -> None:
        component = crypto_component(
            cryptoProperties={
                "assetType": "algorithm",
                "algorithmProperties": {"primitive": "block-cipher", "mode": "gcm"},
            },
            properties=[{"name": "trinetra:algorithm", "value": "aes"}],
        )
        result = ingest_document(
            minimal_document(components=[component]), scan_target=SCAN_TARGET
        )
        detail = result.artefacts[0].detail

        assert detail is not None
        assert detail.key_size_bits is None
        assert detail.mode is CipherMode.GCM

    def test_zero_key_size_is_not_a_measurement(self) -> None:
        """A zero key size is not a measurement of zero bits.

        The component states no parameterSetIdentifier either, so there is
        genuinely nothing to fall back to and the field must stay None.
        """
        component = crypto_component(
            cryptoProperties={
                "assetType": "algorithm",
                "algorithmProperties": {"primitive": "pke"},
            },
            properties=[{"name": "trinetra:key-size-bits", "value": "0"}],
        )
        result = ingest_document(
            minimal_document(components=[component]), scan_target=SCAN_TARGET
        )
        detail = result.artefacts[0].detail
        assert detail is None or detail.key_size_bits is None

    def test_key_size_property_wins_over_parameter_set(self) -> None:
        """The explicit property is preferred over parameterSetIdentifier.

        parameterSetIdentifier is a string that also carries non-numeric names
        such as ML-KEM-768, so the unambiguous property is authoritative.
        """
        component = crypto_component(
            cryptoProperties={
                "assetType": "algorithm",
                "algorithmProperties": {"parameterSetIdentifier": "1024"},
            },
            properties=[{"name": "trinetra:key-size-bits", "value": "4096"}],
        )
        result = ingest_document(
            minimal_document(components=[component]), scan_target=SCAN_TARGET
        )
        assert result.artefacts[0].detail.key_size_bits == 4096

    def test_non_numeric_parameter_set_is_kept_as_a_name(self) -> None:
        """ML-KEM-768 is a parameter set name, not a key size."""
        component = crypto_component(
            name="ML-KEM-768",
            cryptoProperties={
                "assetType": "algorithm",
                "algorithmProperties": {
                    "primitive": "kem",
                    "parameterSetIdentifier": "ML-KEM-768",
                },
            },
            properties=[],
        )
        result = ingest_document(
            minimal_document(components=[component]), scan_target=SCAN_TARGET
        )
        detail = result.artefacts[0].detail
        assert detail.parameter_set == "ML-KEM-768"
        assert detail.key_size_bits is None

    def test_unstated_confidence_is_low_not_high(self) -> None:
        component = crypto_component(properties=[])
        result = ingest_document(
            minimal_document(components=[component]), scan_target=SCAN_TARGET
        )
        assert result.artefacts[0].evidence[0].confidence is Confidence.LOW


class TestLibraryFindings:
    """OpenSSL being installed proves an implementation exists, not a use."""

    def test_library_carries_no_algorithm(self) -> None:
        component = crypto_component(
            name="OpenSSL",
            cryptoProperties={"assetType": "library"},
            properties=[{"name": "trinetra:algorithm", "value": "rsa"}],
        )
        result = ingest_document(
            minimal_document(components=[component]), scan_target=SCAN_TARGET
        )
        artefact = result.artefacts[0]

        assert artefact.asset_type is AssetType.LIBRARY
        assert artefact.algorithm is None


class TestAssetTypeRoundTrip:
    def test_key_survives_the_shared_wire_spelling(self) -> None:
        """key, hardware_module and cloud_service share one CycloneDX value."""
        component = crypto_component(
            name="rsa-private-key",
            cryptoProperties={"assetType": "related-crypto-material"},
            properties=[{"name": "trinetra:asset-type", "value": "key"}],
        )
        result = ingest_document(
            minimal_document(components=[component]), scan_target=SCAN_TARGET
        )
        assert result.artefacts[0].asset_type is AssetType.KEY

    def test_unknown_asset_type_degrades_rather_than_failing(self) -> None:
        """Ingesting a third-party CBOM with a newer type should not fail."""
        component = crypto_component(
            cryptoProperties={"assetType": "some-future-type"}
        )
        result = ingest_document(
            minimal_document(components=[component]), scan_target=SCAN_TARGET
        )
        assert result.artefacts[0].asset_type is AssetType.ALGORITHM


class TestGoldenDocument:
    """The vertical slice: real scanner output through real ingest."""

    def test_golden_document_validates(self, golden_document: dict) -> None:
        validate_document(golden_document)

    def test_golden_document_ingests(self, golden_document: dict) -> None:
        result = ingest_document(
            golden_document,
            scan_target=SCAN_TARGET,
            discovered_by=ScannerKind.SOURCE,
        )
        assert result.artefact_count > 0
        assert result.gaps == [], f"unexpected gaps: {result.gaps}"

    def test_key_sizes_survive_source_to_artefact(self, golden_document: dict) -> None:
        """The message-interpolation contract, end to end.

        A key size travels: source line -> Semgrep message -> CBOM property ->
        artefact field. Any break in that chain silently degrades findings to
        NEEDS_CONTEXT, so it is asserted on real output.
        """
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)
        sized = [
            a
            for a in result.artefacts
            if a.detail is not None and getattr(a.detail, "key_size_bits", None)
        ]
        assert sized, "no artefact carried a key size"
        assert any(a.detail.key_size_bits == 2048 for a in sized)

    def test_modes_survive(self, golden_document: dict) -> None:
        """R19: 'AES' alone is not an answer; AES-CBC and AES-ECB are."""
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)
        modes = {
            a.detail.mode
            for a in result.artefacts
            if a.detail is not None and getattr(a.detail, "mode", None)
        }
        assert CipherMode.CBC in modes
        assert CipherMode.ECB in modes, "ECB is a finding in its own right"

    def test_every_artefact_has_verifiable_evidence(
        self, golden_document: dict
    ) -> None:
        """An unsourced finding is a bug, not a low-quality artefact."""
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)
        for artefact in result.artefacts:
            assert artefact.evidence, f"{artefact.name} has no evidence"
            assert artefact.evidence[0].location.path
            assert artefact.evidence[0].location.line

    def test_tool_versions_are_recorded(self, golden_document: dict) -> None:
        result = ingest_document(golden_document, scan_target=SCAN_TARGET)
        names = {t.name for t in result.tools}
        assert "source-scanner" in names
        assert any("semgrep" in n for n in names)

    def test_ingest_is_idempotent(self, golden_document: dict) -> None:
        """Deterministic ids mean re-ingesting yields the same artefact set."""
        first = ingest_document(golden_document, scan_target=SCAN_TARGET)
        second = ingest_document(golden_document, scan_target=SCAN_TARGET)

        assert {a.artefact_id for a in first.artefacts} == {
            a.artefact_id for a in second.artefacts
        }

    def test_taint_evidence_reaches_ingest(self, golden_document: dict) -> None:
        """Mosca's X depends on this scanner-evidence tier existing."""
        categories = {
            p["value"]
            for component in golden_document["components"]
            for p in component.get("properties", [])
            if p["name"] == "trinetra:data-category"
        }
        assert categories, "no data-category property in the golden document"
