/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Restore
         * @description Restore a cookie-authenticated browser session with a fresh CSRF token.
         *
         *     The access token remains HttpOnly; the short-lived anti-CSRF value is held
         *     only in the running client after this response.
         */
        get: operations["session_restore_api_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        /** Provision User */
        post: operations["provision_user_api_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/scans/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Capabilities */
        get: operations["scan_capabilities_api_scans_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scans */
        get: operations["list_scans_api_scans_get"];
        put?: never;
        /** Create Scan */
        post: operations["create_scan_api_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_api_scans__scan_id__get"];
        put?: never;
        post?: never;
        /** Delete Scan */
        delete: operations["delete_scan_api_scans__scan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Scan */
        post: operations["cancel_scan_api_scans__scan_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescan */
        post: operations["rescan_api_scans__scan_id__rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Progress */
        get: operations["scan_progress_api_scans__scan_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Events */
        get: operations["scan_events_api_scans__scan_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/artefacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Artefacts */
        get: operations["scan_artefacts_api_scans__scan_id__artefacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artefacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Artefacts */
        get: operations["query_artefacts_api_artefacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artefacts/bulk-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Review Artefacts
         * @description Persist analyst dispositions; they are never mere client-side labels.
         */
        post: operations["bulk_review_artefacts_api_artefacts_bulk_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artefacts/{artefact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artefact */
        get: operations["get_artefact_api_artefacts__artefact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artefacts/{artefact_id}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Risk
         * @description Return the current reproducible two-track verdict without recomputing it.
         */
        get: operations["get_risk_api_artefacts__artefact_id__risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artefacts/{artefact_id}/mosca": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mosca
         * @description Expose Mosca inputs and provenance separately from the score.
         */
        get: operations["get_mosca_api_artefacts__artefact_id__mosca_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artefacts/{artefact_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Context */
        patch: operations["update_context_api_artefacts__artefact_id__context_patch"];
        trace?: never;
    };
    "/api/artefacts/{artefact_id}/what-if": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** What If */
        post: operations["what_if_api_artefacts__artefact_id__what_if_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_api_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_api_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Application */
        put: operations["update_application_api_applications__application_id__put"];
        post?: never;
        /** Delete Application */
        delete: operations["delete_application_api_applications__application_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Applications */
        post: operations["import_applications_api_applications_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/risk-presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Risk Preset */
        get: operations["get_risk_preset_api_settings_risk_presets_get"];
        put?: never;
        /** Set Risk Preset */
        post: operations["set_risk_preset_api_settings_risk_presets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recommendations */
        get: operations["list_recommendations_api_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scans/{scan_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Report */
        post: operations["create_report_api_scans__scan_id__reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Report */
        get: operations["download_report_api_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Summary */
        get: operations["dashboard_summary_api_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplicationRequest */
        ApplicationRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Owner */
            owner?: string | null;
            /** Owner Email */
            owner_email?: string | null;
            /** @default unknown */
            business_criticality: components["schemas"]["BusinessCriticality"];
            /** @default unknown */
            data_classification: components["schemas"]["DataClassification"];
            /** @default unknown */
            exposure: components["schemas"]["ExposureLevel"];
            /** Data Retention Years */
            data_retention_years?: number | null;
            /** Migration Time Years */
            migration_time_years?: number | null;
            /** Tags */
            tags?: string[];
        };
        /** ApplicationResponse */
        ApplicationResponse: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Owner */
            owner?: string | null;
            /** Owner Email */
            owner_email?: string | null;
            /** @default unknown */
            business_criticality: components["schemas"]["BusinessCriticality"];
            /** @default unknown */
            data_classification: components["schemas"]["DataClassification"];
            /** @default unknown */
            exposure: components["schemas"]["ExposureLevel"];
            /** Data Retention Years */
            data_retention_years?: number | null;
            /** Migration Time Years */
            migration_time_years?: number | null;
            /** Tags */
            tags?: string[];
            /** Id */
            id: string;
            /** Project Id */
            project_id?: string | null;
        };
        /** ArtefactFacets */
        ArtefactFacets: {
            /** Type */
            type?: {
                [key: string]: number;
            };
            /** Priority */
            priority?: {
                [key: string]: number;
            };
            /** Application */
            application?: {
                [key: string]: number;
            };
            /** Algorithm */
            algorithm?: {
                [key: string]: number;
            };
            /** Quantum Status */
            quantum_status?: {
                [key: string]: number;
            };
            /** Scanner */
            scanner?: {
                [key: string]: number;
            };
        };
        /** ArtefactListItem */
        ArtefactListItem: {
            /** Id */
            id: string;
            /** Scan Id */
            scan_id: string;
            /** Application Id */
            application_id?: string | null;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Algorithm */
            algorithm?: string | null;
            /** Key Size Bits */
            key_size_bits?: number | null;
            /** Location */
            location?: string | null;
            /** Discovered By */
            discovered_by: string;
            /** Quantum Vulnerability */
            quantum_vulnerability: string;
            /** Risk Score */
            risk_score?: number | null;
            /**
             * Priority
             * @default none
             */
            priority: string;
            /** Assessment Status */
            assessment_status?: string | null;
            /** Recommendation */
            recommendation?: string | null;
            /** Review Status */
            review_status?: string | null;
            /** Review Owner */
            review_owner?: string | null;
            /** Review Reason */
            review_reason?: string | null;
        };
        /** ArtefactListResponse */
        ArtefactListResponse: {
            /** Items */
            items: components["schemas"]["ArtefactListItem"][];
            page: components["schemas"]["PageMeta"];
            facets: components["schemas"]["ArtefactFacets"];
            scan_status?: components["schemas"]["ScanStatus"] | null;
            /**
             * Partial Results
             * @default false
             */
            partial_results: boolean;
        };
        /** BulkReviewRequest */
        BulkReviewRequest: {
            /** Artefact Ids */
            artefact_ids: string[];
            /**
             * Action
             * @enum {string}
             */
            action: "accept_risk" | "assign_owner" | "false_positive" | "clear";
            /** Owner */
            owner?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** BulkReviewResponse */
        BulkReviewResponse: {
            /** Updated */
            updated: number;
        };
        /**
         * BusinessCriticality
         * @description Business criticality of the owning system.
         *
         *     A string enum rather than a bare 1-5 integer so that an unset value is
         *     ``unknown`` and visibly so, rather than silently becoming 3 (P3).
         * @enum {string}
         */
        BusinessCriticality: "critical" | "high" | "medium" | "low" | "unknown";
        /** ContextPatchRequest */
        ContextPatchRequest: {
            /** Application Id */
            application_id?: string | null;
            business_criticality?: components["schemas"]["BusinessCriticality"] | null;
            data_classification?: components["schemas"]["DataClassification"] | null;
            exposure?: components["schemas"]["ExposureLevel"] | null;
            /** Data Category */
            data_category?: string | null;
            /** Data Lifetime Years */
            data_lifetime_years?: number | null;
            /** Migration Time Years */
            migration_time_years?: number | null;
            /** Retention Evidence */
            retention_evidence?: components["schemas"]["RetentionEvidence"][] | null;
        };
        /**
         * CsvImportRequest
         * @description CMDB export body.  CSV is explicit rather than inferred from a file name.
         */
        CsvImportRequest: {
            /** Csv Content */
            csv_content: string;
        };
        /** DashboardApplication */
        DashboardApplication: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /** At Risk Count */
            at_risk_count: number;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Scan Count */
            scan_count: number;
            /** Priority Counts */
            priority_counts: {
                [key: string]: number;
            };
            /** Needs Context Count */
            needs_context_count: number;
            /** Worst Offenders */
            worst_offenders: components["schemas"]["ArtefactListItem"][];
            /**
             * Total Artefacts
             * @default 0
             */
            total_artefacts: number;
            /**
             * Quantum Vulnerable Count
             * @default 0
             */
            quantum_vulnerable_count: number;
            /** Quantum Safe Percent */
            quantum_safe_percent?: number | null;
            /** Nearest Mosca Deadline Year */
            nearest_mosca_deadline_year?: number | null;
            /** Artefact Type Counts */
            artefact_type_counts?: {
                [key: string]: number;
            };
            /** Top Applications */
            top_applications?: components["schemas"]["DashboardApplication"][];
            /** Trend */
            trend?: components["schemas"]["DashboardTrendPoint"][];
        };
        /** DashboardTrendPoint */
        DashboardTrendPoint: {
            /** Scan Id */
            scan_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Artefact Count */
            artefact_count: number;
            /** Critical Count */
            critical_count: number;
        };
        /**
         * DataClassification
         * @enum {string}
         */
        DataClassification: "restricted" | "confidential" | "internal" | "public" | "unknown";
        /**
         * EvidenceSource
         * @description Ranked sources for the confidentiality lifetime X.
         * @enum {string}
         */
        EvidenceSource: "user" | "scanner" | "org_policy" | "legal_profile";
        /**
         * ExposureLevel
         * @description Network reachability of the system holding the artefact.
         *
         *     Drives HNDL urgency: internet-exposed traffic can be recorded today by an
         *     adversary with no access to the network, which is what makes it the
         *     highest-priority confidentiality risk.
         * @enum {string}
         */
        ExposureLevel: "internet" | "partner" | "internal" | "isolated" | "unknown";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResponse */
        ImportResponse: {
            /** Created */
            created: number;
            /** Updated */
            updated: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors?: string[];
        };
        /** PageMeta */
        PageMeta: {
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
        };
        /** ProjectCreateRequest */
        ProjectCreateRequest: {
            /** Name */
            name: string;
            /** Tenant Id */
            tenant_id: string;
            /** Description */
            description?: string | null;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ReportCreateRequest */
        ReportCreateRequest: {
            /** Format */
            format: string;
        };
        /** ReportResponse */
        ReportResponse: {
            /** Id */
            id: string;
            /** Scan Id */
            scan_id: string;
            /** Format */
            format: string;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Checksum Sha256 */
            checksum_sha256?: string | null;
        };
        /**
         * ResourceScenario
         * @description Scales the capability curve P(t) -- never the attack requirement Q.
         * @enum {string}
         */
        ResourceScenario: "conservative" | "baseline" | "aggressive";
        /**
         * RetentionBasis
         * @description What backs a retention figure.
         *
         *     ``regulatory_minimum`` carries an explicit caveat: Indian statutes mandate
         *     retention *minimums*, not confidentiality lifetimes, and the two are not
         *     interchangeable.
         * @enum {string}
         */
        RetentionBasis: "legal" | "regulatory_minimum" | "assumption";
        /**
         * RetentionEvidence
         * @description One piece of evidence for the confidentiality lifetime X.
         */
        RetentionEvidence: {
            source: components["schemas"]["EvidenceSource"];
            /**
             * Data Category
             * @description e.g. aadhaar_pii, health_record, session_token.
             */
            data_category: string;
            /** Lifetime Years */
            lifetime_years: number;
            basis: components["schemas"]["RetentionBasis"];
            /**
             * Citation
             * @description Statute, policy id or profile entry.
             */
            citation?: string | null;
            /**
             * Caveat
             * @description Printed with the figure wherever it appears. Retention minimums in particular are not confidentiality lifetimes.
             */
            caveat?: string | null;
        };
        /** RiskPresetRequest */
        RiskPresetRequest: {
            /** Planning Horizon Years */
            planning_horizon_years?: number | null;
            /** @default baseline */
            scenario: components["schemas"]["ResourceScenario"];
            /** Rule Pack Toggles */
            rule_pack_toggles?: {
                [key: string]: boolean;
            };
        };
        /** RiskPresetResponse */
        RiskPresetResponse: {
            /** Planning Horizon Years */
            planning_horizon_years?: number | null;
            /** @default baseline */
            scenario: components["schemas"]["ResourceScenario"];
            /** Rule Pack Toggles */
            rule_pack_toggles?: {
                [key: string]: boolean;
            };
            /** Version */
            version: string;
            /** Policy Version */
            policy_version: string;
            /** Weights Version */
            weights_version: string;
            /** Quantum Forecast Profile Version */
            quantum_forecast_profile_version: string;
            /** Artefacts Rescored */
            artefacts_rescored: number;
            /** Recommendations Created */
            recommendations_created: number;
        };
        /** ScanCreateRequest */
        ScanCreateRequest: {
            target_kind: components["schemas"]["ScanTargetKind"];
            /** Target Identifier */
            target_identifier: string;
            /** Target Reference */
            target_reference?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Application Id */
            application_id?: string | null;
            /** Scanners */
            scanners?: components["schemas"]["ScannerKind"][];
        };
        /** ScanListResponse */
        ScanListResponse: {
            /** Items */
            items: components["schemas"]["ScanResponse"][];
            page: components["schemas"]["PageMeta"];
        };
        /** ScanProgressResponse */
        ScanProgressResponse: {
            /** Sequence */
            sequence: number;
            /** Percent */
            percent: number;
            /** Stage */
            stage: string;
            /** Counts */
            counts?: {
                [key: string]: number;
            };
            /** Message */
            message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ScanResponse */
        ScanResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id?: string | null;
            target_kind: components["schemas"]["ScanTargetKind"];
            /** Target Identifier */
            target_identifier: string;
            /** Target Reference */
            target_reference?: string | null;
            /** Display Name */
            display_name?: string | null;
            status: components["schemas"]["ScanStatus"];
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Artefact Count
             * @default 0
             */
            artefact_count: number;
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ScanStatus
         * @description A scan must always reach a terminal state.
         *
         *     ``RUNNING`` that never ends is the failure mode with no user-visible end, so
         *     the worker guarantees a transition to ``FAILED`` on any unhandled error.
         * @enum {string}
         */
        ScanStatus: "queued" | "running" | "succeeded" | "partial" | "failed" | "cancelled";
        /**
         * ScanTargetKind
         * @enum {string}
         */
        ScanTargetKind: "git_repository" | "local_path" | "container_image" | "binary_file" | "network_endpoint" | "cloud_account";
        /**
         * ScannerKind
         * @enum {string}
         */
        ScannerKind: "source" | "container" | "cloud_hsm" | "network" | "binary";
        /**
         * SessionResponse
         * @description Cookie-session restoration without exposing a long-lived access token.
         */
        SessionResponse: {
            /** Csrf Token */
            csrf_token: string;
            user: components["schemas"]["UserResponse"];
        };
        /** TokenRequest */
        TokenRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            /** Csrf Token */
            csrf_token: string;
            user: components["schemas"]["UserResponse"];
        };
        /** UserProvisionRequest */
        UserProvisionRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Email */
            email?: string | null;
            /** @default viewer */
            role: components["schemas"]["UserRole"];
            /** Project Ids */
            project_ids?: string[];
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Email */
            email?: string | null;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "analyst" | "viewer";
        /** UserUpdateRequest */
        UserUpdateRequest: {
            role?: components["schemas"]["UserRole"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WhatIfRequest */
        WhatIfRequest: {
            /** Z Years */
            z_years?: number | null;
            /** X Years */
            x_years?: number | null;
            scenario?: components["schemas"]["ResourceScenario"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    session_restore_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    provision_user_api_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProvisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_capabilities_api_scans_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: string;
                        }[];
                    };
                };
            };
        };
    };
    list_scans_api_scans_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scan_api_scans_post: {
        parameters: {
            query?: {
                idempotency_key?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_api_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scan_api_scans__scan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scan_api_scans__scan_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescan_api_scans__scan_id__rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_progress_api_scans__scan_id__progress_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanProgressResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_events_api_scans__scan_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_artefacts_api_scans__scan_id__artefacts_get: {
        parameters: {
            query?: {
                type?: string | null;
                priority?: string | null;
                application_id?: string | null;
                algorithm?: string | null;
                quantum_status?: string | null;
                scanner?: string | null;
                q?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtefactListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_artefacts_api_artefacts_get: {
        parameters: {
            query?: {
                type?: string | null;
                priority?: string | null;
                application_id?: string | null;
                algorithm?: string | null;
                quantum_status?: string | null;
                scanner?: string | null;
                q?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtefactListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_review_artefacts_api_artefacts_bulk_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artefact_api_artefacts__artefact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artefact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_risk_api_artefacts__artefact_id__risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artefact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mosca_api_artefacts__artefact_id__mosca_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artefact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_context_api_artefacts__artefact_id__context_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artefact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    what_if_api_artefacts__artefact_id__what_if_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artefact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_api_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"][];
                };
            };
        };
    };
    create_application_api_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_api_applications__application_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_api_applications__application_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_applications_api_applications_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CsvImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_risk_preset_api_settings_risk_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskPresetResponse"];
                };
            };
        };
    };
    set_risk_preset_api_settings_risk_presets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskPresetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskPresetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recommendations_api_recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    create_report_api_scans__scan_id__reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_report_api_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_summary_api_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
}
