"""Initial schema: scans, artefacts, contexts, assessments, recommendations

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-09-17 12:26:12.980200
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# JSONB on PostgreSQL, plain JSON elsewhere so the test suite can run on SQLite.
JSONColumn = postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), "sqlite")

revision: str = '0001_initial_schema'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=320), nullable=True),
    sa.Column('business_criticality', sa.String(length=32), nullable=False),
    sa.Column('data_classification', sa.String(length=32), nullable=False),
    sa.Column('exposure', sa.String(length=32), nullable=False),
    sa.Column('data_retention_years', sa.Integer(), nullable=True),
    sa.Column('migration_time_years', sa.Float(), nullable=True),
    sa.Column('tags', JSONColumn, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('data_retention_years IS NULL OR data_retention_years >= 0', name=op.f('ck_applications_data_retention_non_negative')),
    sa.CheckConstraint('migration_time_years IS NULL OR migration_time_years >= 0', name=op.f('ck_applications_migration_time_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index('ix_applications_name', 'applications', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('org_setting_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings_json', JSONColumn, nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=True),
    sa.Column('weights_version', sa.String(length=64), nullable=True),
    sa.Column('quantum_forecast_profile_version', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_org_setting_versions_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_setting_versions')),
    sa.UniqueConstraint('version', name=op.f('uq_org_setting_versions_version'))
    )
    op.create_index('ix_org_setting_versions_active', 'org_setting_versions', ['is_active'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_identifier', sa.String(length=1024), nullable=False),
    sa.Column('target_reference', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('scanners_run', JSONColumn, nullable=True),
    sa.Column('tool_versions', JSONColumn, nullable=True),
    sa.Column('coverage_json', JSONColumn, nullable=True),
    sa.Column('errors_json', JSONColumn, nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_scans_requested_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans')),
    sa.UniqueConstraint('requested_by', 'idempotency_key', name='uq_scans_requester_idempotency')
    )
    op.create_index('ix_scans_requested_by', 'scans', ['requested_by'], unique=False)
    op.create_index('ix_scans_status', 'scans', ['status'], unique=False)
    op.create_table('artefacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('algorithm', sa.String(length=255), nullable=True),
    sa.Column('oid', sa.String(length=128), nullable=True),
    sa.Column('primitive', sa.String(length=32), nullable=True),
    sa.Column('purpose', JSONColumn, nullable=True),
    sa.Column('key_size_bits', sa.Integer(), nullable=True),
    sa.Column('size_or_version', sa.String(length=128), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('padding', sa.String(length=32), nullable=True),
    sa.Column('curve', sa.String(length=64), nullable=True),
    sa.Column('quantum_vulnerability', sa.String(length=32), nullable=False),
    sa.Column('nist_security_level', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=1024), nullable=True),
    sa.Column('used_for', sa.Text(), nullable=True),
    sa.Column('observed_data_category', sa.String(length=128), nullable=True),
    sa.Column('discovered_by', sa.String(length=32), nullable=False),
    sa.Column('detail_json', JSONColumn, nullable=True),
    sa.Column('evidence_json', JSONColumn, nullable=True),
    sa.Column('raw_cbom', JSONColumn, nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type <> 'library' OR algorithm IS NULL", name=op.f('ck_artefacts_library_has_no_algorithm')),
    sa.CheckConstraint('key_size_bits IS NULL OR key_size_bits > 0', name=op.f('ck_artefacts_key_size_positive')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_artefacts_application_id_applications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_artefacts_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artefacts'))
    )
    op.create_index('ix_artefacts_application_id', 'artefacts', ['application_id'], unique=False)
    op.create_index('ix_artefacts_name', 'artefacts', ['name'], unique=False)
    op.create_index('ix_artefacts_scan_id', 'artefacts', ['scan_id'], unique=False)
    op.create_index('ix_artefacts_type', 'artefacts', ['type'], unique=False)
    op.create_table('dependency_edges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_id <> target_id', name=op.f('ck_dependency_edges_no_self_edge')),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_dependency_edges_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dependency_edges')),
    sa.UniqueConstraint('scan_id', 'source_id', 'target_id', 'relation', name='uq_dependency_edges_edge')
    )
    op.create_index('ix_dependency_edges_scan_id', 'dependency_edges', ['scan_id'], unique=False)
    op.create_index('ix_dependency_edges_source_id', 'dependency_edges', ['source_id'], unique=False)
    op.create_index('ix_dependency_edges_target_id', 'dependency_edges', ['target_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_reports_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_reports_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('requested_by', 'idempotency_key', name='uq_reports_requester_idempotency')
    )
    op.create_index('ix_reports_scan_id', 'reports', ['scan_id'], unique=False)
    op.create_table('artefact_contexts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('artefact_id', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.String(length=64), nullable=True),
    sa.Column('business_criticality', sa.String(length=32), nullable=False),
    sa.Column('data_classification', sa.String(length=32), nullable=False),
    sa.Column('exposure', sa.String(length=32), nullable=False),
    sa.Column('data_category', sa.String(length=128), nullable=True),
    sa.Column('data_lifetime_years', sa.Integer(), nullable=True),
    sa.Column('migration_time_years', sa.Float(), nullable=True),
    sa.Column('retention_evidence_json', JSONColumn, nullable=True),
    sa.Column('provenance_json', JSONColumn, nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('data_lifetime_years IS NULL OR data_lifetime_years >= 0', name=op.f('ck_artefact_contexts_lifetime_non_negative')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_artefact_contexts_application_id_applications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefacts.id'], name=op.f('fk_artefact_contexts_artefact_id_artefacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artefact_contexts')),
    sa.UniqueConstraint('artefact_id', name=op.f('uq_artefact_contexts_artefact_id'))
    )
    op.create_index('ix_artefact_contexts_artefact_id', 'artefact_contexts', ['artefact_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('artefact_id', sa.String(length=64), nullable=False),
    sa.Column('scan_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('final_confidence', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('mosca_x_years', sa.Integer(), nullable=True),
    sa.Column('mosca_y_years', sa.Float(), nullable=True),
    sa.Column('mosca_z_years', sa.Float(), nullable=True),
    sa.Column('mosca_z_basis', sa.String(length=32), nullable=False),
    sa.Column('mosca_is_urgent', sa.Boolean(), nullable=True),
    sa.Column('mosca_shortfall_years', sa.Float(), nullable=True),
    sa.Column('mosca_evidence_json', JSONColumn, nullable=True),
    sa.Column('resource_m_years', sa.Float(), nullable=True),
    sa.Column('resource_scenario', sa.String(length=32), nullable=False),
    sa.Column('resource_assumptions_json', JSONColumn, nullable=True),
    sa.Column('attack_threshold_json', JSONColumn, nullable=True),
    sa.Column('forecast_capability_json', JSONColumn, nullable=True),
    sa.Column('projected_break_year', sa.Integer(), nullable=True),
    sa.Column('migration_deadline_year', sa.Integer(), nullable=True),
    sa.Column('quantum_projection_status', sa.String(length=32), nullable=False),
    sa.Column('score_contributions_json', JSONColumn, nullable=True),
    sa.Column('missing_fields_json', JSONColumn, nullable=True),
    sa.Column('input_provenance_json', JSONColumn, nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('weights_version', sa.String(length=64), nullable=False),
    sa.Column('quantum_forecast_profile_version', sa.String(length=64), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'scored' AND final_score IS NOT NULL) OR (status <> 'scored' AND final_score IS NULL)", name=op.f('ck_risk_assessments_score_matches_status')),
    sa.CheckConstraint("final_score IS NOT NULL OR priority = 'none'", name=op.f('ck_risk_assessments_unscored_has_no_priority')),
    sa.CheckConstraint('final_score IS NULL OR (final_score >= 0 AND final_score <= 100)', name=op.f('ck_risk_assessments_score_in_range')),
    sa.ForeignKeyConstraint(['artefact_id'], ['artefacts.id'], name=op.f('fk_risk_assessments_artefact_id_artefacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_risk_assessments_scan_id_scans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    op.create_index('ix_risk_assessments_artefact_id', 'risk_assessments', ['artefact_id'], unique=False)
    op.create_index('ix_risk_assessments_assessed_at', 'risk_assessments', ['assessed_at'], unique=False)
    op.create_index('ix_risk_assessments_priority', 'risk_assessments', ['priority'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('recommended_algorithm', sa.String(length=255), nullable=True),
    sa.Column('recommended_parameter_set', sa.String(length=128), nullable=True),
    sa.Column('is_hybrid', sa.Boolean(), nullable=False),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('fit_breakdown_json', JSONColumn, nullable=True),
    sa.Column('latency_impact_json', JSONColumn, nullable=True),
    sa.Column('cost_estimate_json', JSONColumn, nullable=True),
    sa.Column('migration_wave', sa.Integer(), nullable=True),
    sa.Column('profile_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.id'], name=op.f('fk_recommendations_assessment_id_risk_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    sa.UniqueConstraint('assessment_id', name=op.f('uq_recommendations_assessment_id'))
    )
    op.create_index('ix_recommendations_assessment_id', 'recommendations', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recommendations_assessment_id', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_risk_assessments_priority', table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_assessed_at', table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_artefact_id', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index('ix_artefact_contexts_artefact_id', table_name='artefact_contexts')
    op.drop_table('artefact_contexts')
    op.drop_index('ix_reports_scan_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_dependency_edges_target_id', table_name='dependency_edges')
    op.drop_index('ix_dependency_edges_source_id', table_name='dependency_edges')
    op.drop_index('ix_dependency_edges_scan_id', table_name='dependency_edges')
    op.drop_table('dependency_edges')
    op.drop_index('ix_artefacts_type', table_name='artefacts')
    op.drop_index('ix_artefacts_scan_id', table_name='artefacts')
    op.drop_index('ix_artefacts_name', table_name='artefacts')
    op.drop_index('ix_artefacts_application_id', table_name='artefacts')
    op.drop_table('artefacts')
    op.drop_index('ix_scans_status', table_name='scans')
    op.drop_index('ix_scans_requested_by', table_name='scans')
    op.drop_table('scans')
    op.drop_index('ix_org_setting_versions_active', table_name='org_setting_versions')
    op.drop_table('org_setting_versions')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_applications_name', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
