apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trinetra.fullname" . }}-config
  labels:
    {{- include "trinetra.labels" . | nindent 4 }}
data:
  TRINETRA_DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  TRINETRA_CELERY_BROKER_URL: {{ .Values.config.celeryBrokerUrl | quote }}
  TRINETRA_CELERY_RESULT_BACKEND: {{ .Values.config.celeryResultBackend | quote }}
  TRINETRA_RATE_LIMIT_PER_MINUTE: {{ .Values.config.rateLimitPerMinute | quote }}
  TRINETRA_CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  TRINETRA_REPORT_STORE: {{ .Values.config.reportStorePath | quote }}
  TRINETRA_ARTIFACT_STORE: {{ .Values.config.artifactStorePath | quote }}
  TRINETRA_AUTO_CREATE_SCHEMA: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trinetra.fullname" . }}-secret
  labels:
    {{- include "trinetra.labels" . | nindent 4 }}
type: Opaque
stringData:
  TRINETRA_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  BOOTSTRAP_ADMIN_USERNAME: {{ .Values.secrets.bootstrapAdminUser | quote }}
  BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.secrets.bootstrapAdminPassword | quote }}
  TRINETRA_SCANNER_TOKEN: {{ .Values.secrets.scannerToken | quote }}
